<?php

use Illuminate\Database\Seeder;

class ProsystemAdministratorProcessLogsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('prosystem_administrator_process_logs')->delete();
        
		\DB::table('prosystem_administrator_process_logs')->insert(array (
			0 => 
			array (
				'id' => 76,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/users',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/home',
				'url_path_explain' => '/mandev/home',
				'log_process' => 1,
				'msg' => 'access',
				'postdata' => '[]',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778721,
			),
			1 => 
			array (
				'id' => 77,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/users',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/login',
				'url_path_explain' => '/mandev/login',
				'log_process' => 1,
				'msg' => 'access',
				'postdata' => '[]',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778721,
			),
			2 => 
			array (
				'id' => 78,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/login',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/login',
				'url_path_explain' => '/mandev/login',
				'log_process' => 2,
				'msg' => 'access',
				'postdata' => '{"_token":"oG6eMdyv87rWpZkTaBY1UVcpVl5EYzfqlQBGaVom","ccode":"devSde","username":"aligurbuz","password":"280384483082"}',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778727,
			),
			3 => 
			array (
				'id' => 79,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/login',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/home',
				'url_path_explain' => '/mandev/home',
				'log_process' => 1,
				'msg' => 'access',
				'postdata' => '[]',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778727,
			),
			4 => 
			array (
				'id' => 80,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/login',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/home',
				'url_path_explain' => '/mandev/home',
				'log_process' => 1,
				'msg' => 'access',
				'postdata' => '[]',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778766,
			),
			5 => 
			array (
				'id' => 81,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/login',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/home',
				'url_path_explain' => '/mandev/home',
				'log_process' => 1,
				'msg' => 'access',
				'postdata' => '[]',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778852,
			),
			6 => 
			array (
				'id' => 82,
				'userid' => 1,
				'userip' => '127.0.0.1',
				'userHash' => NULL,
				'isoCode' => 'US',
				'country' => 'United States',
				'city' => 'New Haven',
				'state' => 'CT',
				'postal_code' => '06510',
				'lat' => 41.310000000000002,
				'lon' => -72.920000000000002,
				'timezone' => 'America/New_York',
				'continent' => 'NA',
				'isMobile' => 0,
				'isTablet' => 0,
				'isDesktop' => 1,
				'isBot' => 0,
				'browserFamily' => 'Chrome',
				'browserVersionMajor' => '0',
				'browserVersionMinor' => '0',
				'browserVersionPatch' => '0',
				'osFamily' => 'MacOSX',
				'osVersionMajor' => '0',
				'osVersionMinor' => '0',
				'osVersionPatch' => '0',
				'deviceFamily' => '',
				'deviceModel' => '',
				'mobileGrade' => '',
				'cssVersion' => '1',
				'javaScriptSupport' => 1,
				'referer' => 'http://localhost:8070/projects/devman/devman/public/mandev/home',
				'formprocess' => 'Normal Request',
			'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
				'user_host' => 'localhost:8070',
				'url_path' => 'http://localhost:8070/projects/devman/devman/public/mandev/home',
				'url_path_explain' => '/mandev/home',
				'log_process' => 1,
				'msg' => 'access',
				'postdata' => '[]',
				'noauth_area_operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'created_at' => 1452778908,
			),
		));
	}

}
