<?php

use Illuminate\Database\Seeder;

class ProsystemAdministratorTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('prosystem_administrator')->delete();
        
		\DB::table('prosystem_administrator')->insert(array (
			0 => 
			array (
				'id' => 1,
				'ccode' => 'devSde',
				'username' => 'aligurbuz',
				'password' => '7ada520f7fb0eb935a11f392511fe86e',
				'email' => 'galiant781@gmail.com',
				'hash' => '534882c92305e57fc21c495ad6cb151f',
				'fullname' => 'Ali Bilge Gürbüz',
				'last_ip' => '127.0.0.1',
				'created_at' => 1447331070,
				'updated_at' => 1452773254,
				'photo' => '48832.jpg',
				'extra_info' => 'it can be written later',
				'lang' => 1,
				'user_lock' => 1,
				'role' => '1-2-3',
				'system_name' => 'Developer
',
				'system_number' => 0,
				'phone_number' => '0545 906 29 92',
				'address' => 'İstanbul',
				'occupation' => 'Software Developer',
				'website' => 'http://sw.devx.net',
				'last_login_time' => 1452773031,
				'user_where' => '/mandev/users',
				'status' => 1,
				'logout' => 0,
				'logout_time' => 0,
				'created_by' => NULL,
				'is_mobile' => 0,
				'is_tablet' => 0,
				'is_desktop' => 1,
				'is_bot' => 0,
				'browser_family' => 'Chrome',
				'os_family' => 'MacOSX',
				'all_clicked' => 90,
				'hash_clicked' => 9,
				'operations' => 2,
				'success_operations' => 0,
				'fail_operations' => 2,
				'noauth_area_operations' => 0,
			),
			1 => 
			array (
				'id' => 20,
				'ccode' => 'Promedia',
				'username' => 'zeynep',
				'password' => '4c34b4675bebbe13a3515bb906e943c7',
				'email' => 'zeynep@promedia.com.tr',
				'hash' => '94d914cac515f8a80e68f1313dbbd1cf',
				'fullname' => 'Zeynep Kasarcalı',
				'last_ip' => '127.0.0.1',
				'created_at' => 1452691044,
				'updated_at' => 1452760650,
				'photo' => 'default.png',
				'extra_info' => '',
				'lang' => 1,
				'user_lock' => 1,
				'role' => '1-2-3',
				'system_name' => 'manager',
				'system_number' => 1,
				'phone_number' => '0543 234 56 78',
				'address' => '',
				'occupation' => '',
				'website' => '',
				'last_login_time' => 1452757943,
				'user_where' => '/mandev/logout',
				'status' => 1,
				'logout' => 1,
				'logout_time' => 1452760652,
				'created_by' => 1,
				'is_mobile' => 0,
				'is_tablet' => 0,
				'is_desktop' => 1,
				'is_bot' => 0,
				'browser_family' => 'Chrome',
				'os_family' => 'MacOSX',
				'all_clicked' => 64,
				'hash_clicked' => 0,
				'operations' => 3,
				'success_operations' => 1,
				'fail_operations' => 1,
				'noauth_area_operations' => 0,
			),
			2 => 
			array (
				'id' => 21,
				'ccode' => 'Promedia',
				'username' => 'emrekoca',
				'password' => '0ac9444c86e7c60b520c68e9c3cbaa69',
				'email' => 'emrekoca@promedia.com.tr',
				'hash' => 'e674bb4f7107becde9ace289d25c2a34',
				'fullname' => 'Emre Hakkı Koca',
				'last_ip' => '127.0.0.1',
				'created_at' => 1452691708,
				'updated_at' => 1452773024,
				'photo' => 'default.png',
				'extra_info' => '',
				'lang' => 1,
				'user_lock' => 1,
				'role' => '1-3',
				'system_name' => 'normal',
				'system_number' => 2,
				'phone_number' => '',
				'address' => NULL,
				'occupation' => NULL,
				'website' => NULL,
				'last_login_time' => 1452772915,
				'user_where' => '/mandev/logout',
				'status' => 1,
				'logout' => 1,
				'logout_time' => 1452773027,
				'created_by' => 20,
				'is_mobile' => 0,
				'is_tablet' => 0,
				'is_desktop' => 1,
				'is_bot' => 0,
				'browser_family' => 'Chrome',
				'os_family' => 'MacOSX',
				'all_clicked' => 3,
				'hash_clicked' => 0,
				'operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'noauth_area_operations' => 1,
			),
			3 => 
			array (
				'id' => 26,
				'ccode' => 'Promedia',
				'username' => 'iremkarta',
				'password' => '760400fd30c9a3890d46dbb7f8838b64',
				'email' => 'iremkarta@promedia.com.tr',
				'hash' => '',
				'fullname' => 'İrem Karta',
				'last_ip' => '',
				'created_at' => 1452759362,
				'updated_at' => 0,
				'photo' => 'default.png',
				'extra_info' => '',
				'lang' => 1,
				'user_lock' => 1,
				'role' => '1-3',
				'system_name' => 'normal',
				'system_number' => 2,
				'phone_number' => '',
				'address' => NULL,
				'occupation' => NULL,
				'website' => NULL,
				'last_login_time' => NULL,
				'user_where' => NULL,
				'status' => 1,
				'logout' => 0,
				'logout_time' => 0,
				'created_by' => 20,
				'is_mobile' => NULL,
				'is_tablet' => NULL,
				'is_desktop' => NULL,
				'is_bot' => NULL,
				'browser_family' => NULL,
				'os_family' => NULL,
				'all_clicked' => 0,
				'hash_clicked' => 0,
				'operations' => 0,
				'success_operations' => 0,
				'fail_operations' => 0,
				'noauth_area_operations' => 0,
			),
		));
	}

}
