<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemRolesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemRolesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_roles', function(Blueprint $table) {
$table->integer('id')
      ->unsigned();
$table->string('role_define', 255);
$table->text('role_info');
$table->integer('lang');
$table->integer('created_at');
$table->integer('updated_at');
$table->integer('statu');

$table->primary('id', 'prim');
$table->index(['role_define', 'lang', 'statu'], 'auth_define');
$table->index('lang', 'lang');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_roles');
    }
}