<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemLocationsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemLocationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_locations', function(Blueprint $table) {
$table->increments('id')
      ->unsigned();
$table->string('location', 255);
$table->integer('parent');
$table->string('seo_location', 255);
$table->string('statu', 255);
$table->integer('language');

});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_locations');
    }
}