<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreatePasswordResetsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreatePasswordResetsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('password_resets', function(Blueprint $table) {
$table->string('email', 255);
$table->string('token', 255);
$table->dateTime('created_at')
      ->default('0000-00-00 00:00:00');

$table->index('email', 'password_resets_email_index');
$table->index('token', 'password_resets_token_index');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('password_resets');
    }
}