<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemHotelsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemHotelsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_hotels', function(Blueprint $table) {
$table->integer('id')
      ->unsigned();
$table->string('hotel_name', 255);
$table->string('hotel_search_name', 255);
$table->integer('country');
$table->integer('province');
$table->integer('district');
$table->integer('town');
$table->integer('hotel_type');
$table->float('sea_distinct');
$table->string('sea_unit', 20);
$table->float('bus_distinct');
$table->string('bus_unit', 20);
$table->float('airbus_distinct');
$table->string('airbus_unit', 20);
$table->string('hotel_enable', 5);
$table->text('hotel_description');
$table->text('hotel_tags');
$table->text('hotel_seo');
$table->text('hotel_properties');
$table->text('hotel_base_price_json');

$table->primary('id', 'prim');
$table->index('hotel_name', 'hotel_name');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_hotels');
    }
}