<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemMysqlSlowProcessLogsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemMysqlSlowProcessLogsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_mysql_slow_process_logs', function(Blueprint $table) {
$table->integer('id')
      ->unsigned();
$table->text('url_path');
$table->text('query_log')
      ->nullable()
      ->default(NULL);
$table->text('query_bindings')
      ->nullable()
      ->default(NULL);
$table->float('query_time')
      ->nullable()
      ->default(NULL);
$table->integer('created_at');

$table->primary('id', 'prim');
$table->index('created_at', 'created_at');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_mysql_slow_process_logs');
    }
}