<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateUsersTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateUsersTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('users', function(Blueprint $table) {
$table->bigInteger('id');
$table->string('jabber_id', 50)
      ->nullable()
      ->default(NULL);
$table->string('jabber_password', 89)
      ->nullable()
      ->default(NULL);
$table->string('name', 255);
$table->string('email', 255);
$table->string('password', 255)
      ->nullable()
      ->default(NULL);
$table->boolean('status')
      ->default('1');
$table->string('gender', );
$table->integer('picture_id');
$table->string('picture_url', 100)
      ->nullable()
      ->default(NULL);
$table->integer('picture_count');
$table->string('language', 4);
$table->integer('location_id');
$table->integer('location_last_id');
$table->integer('job');
$table->string('job_name', 100)
      ->nullable()
      ->default(NULL);
$table->bigInteger('facebook_id');
$table->string('info', 1000)
      ->nullable()
      ->default(NULL);
$table->text('about')
      ->nullable()
      ->default(NULL);
$table->integer('relationship');
$table->string('relationship_name', 100)
      ->nullable()
      ->default(NULL);
$table->integer('education');
$table->string('education_name', 100)
      ->nullable()
      ->default(NULL);
$table->integer('sexuality');
$table->string('sexuality_name', 100)
      ->nullable()
      ->default(NULL);
$table->boolean('invisible');
$table->boolean('unlimited');
$table->integer('unlimited_started');
$table->dateTime('unlimited_started_s')
      ->nullable()
      ->default(NULL);
$table->integer('unlimited_finish');
$table->dateTime('unlimited_finish_s')
      ->nullable()
      ->default(NULL);
$table->date('birthday')
      ->nullable()
      ->default(NULL);
$table->integer('created_at');
$table->dateTime('created_at_s')
      ->default('CURRENT_TIMESTAMP');
$table->integer('updated_at');
$table->dateTime('updated_at_s')
      ->default('CURRENT_TIMESTAMP');
$table->bigInteger('ip');
$table->bigInteger('last_ip');
$table->integer('visitor_hit');
$table->integer('credit');

$table->primary('id', 'prim');
$table->index('email', 'email');
$table->index('status', 'active');
$table->index('gender', 'gender');
$table->index('language', 'language');
$table->index('location_id', 'location');
$table->index('facebook_id', 'facebook_id');
$table->index('birthday', 'birthday');
$table->index(['email', 'password'], 'email_2');
$table->index('jabber_id', 'jabber_id');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('users');
    }
}