<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemDefaultRolesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemDefaultRolesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_default_roles', function(Blueprint $table) {
$table->increments('id')
      ->unsigned();
$table->string('role_name', 255)
      ->nullable()
      ->default(NULL);
$table->integer('system_number')
      ->nullable()
      ->default(NULL);
$table->text('roles')
      ->nullable()
      ->default(NULL);
$table->integer('role_row')
      ->nullable()
      ->default(NULL);

});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_default_roles');
    }
}