<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemAdministratorTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemAdministratorTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_administrator', function(Blueprint $table) {
$table->increments('id')
      ->unsigned();
$table->string('ccode', 255)
      ->nullable()
      ->default(NULL);
$table->string('username', 255);
$table->string('password', 255);
$table->string('email', 255)
      ->nullable()
      ->default(NULL);
$table->string('hash', 255);
$table->string('fullname', 255);
$table->string('last_ip', 255);
$table->integer('created_at');
$table->integer('updated_at');
$table->string('photo', 255);
$table->text('extra_info');
$table->integer('lang')
      ->default('1');
$table->integer('user_lock')
      ->nullable()
      ->default('1');
$table->text('role');
$table->string('system_name', 255)
      ->nullable()
      ->default(NULL);
$table->integer('system_number')
      ->nullable()
      ->default(NULL);
$table->string('phone_number', 255)
      ->nullable()
      ->default(NULL);
$table->text('address')
      ->nullable()
      ->default(NULL);
$table->string('occupation', 255)
      ->nullable()
      ->default(NULL);
$table->string('website', 255)
      ->nullable()
      ->default(NULL);
$table->integer('last_login_time')
      ->nullable()
      ->default(NULL);
$table->string('user_where', 255)
      ->nullable()
      ->default(NULL);
$table->integer('status')
      ->nullable()
      ->default('1');
$table->integer('logout')
      ->nullable();
$table->integer('logout_time')
      ->nullable();
$table->integer('created_by')
      ->nullable()
      ->default(NULL);
$table->integer('is_mobile')
      ->nullable()
      ->default(NULL);
$table->integer('is_tablet')
      ->nullable()
      ->default(NULL);
$table->integer('is_desktop')
      ->nullable()
      ->default(NULL);
$table->integer('is_bot')
      ->nullable()
      ->default(NULL);
$table->string('browser_family', 255)
      ->nullable()
      ->default(NULL);
$table->string('os_family', 255)
      ->nullable()
      ->default(NULL);
$table->integer('all_clicked')
      ->nullable();
$table->integer('hash_clicked')
      ->nullable();
$table->integer('operations')
      ->nullable();
$table->integer('success_operations')
      ->nullable();
$table->integer('fail_operations')
      ->nullable();
$table->integer('noauth_area_operations')
      ->nullable();

$table->index('username', 'username');
$table->index('password', 'password');
$table->index('hash', 'hash');
$table->index('updated_at', 'updated_at');
$table->index('system_number', 'system_number');
$table->index('status', 'status');
$table->index('logout', 'logout');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_administrator');
    }
}