<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProsystemApiAccessesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProsystemApiAccessesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('prosystem_api_accesses', function(Blueprint $table) {
$table->integer('id')
      ->unsigned();
$table->string('ccode', 100);
$table->string('ip', 20);
$table->string('apikey', 50);
$table->integer('statu');

$table->primary('id', 'prim');
});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('prosystem_api_accesses');
    }
}